name: Sync Organization Repo

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          # repository: organization-name/organization-repo-name
          repository: 3legant-E-commerce/MainApp
          token: ${{ secrets.GH_TOKEN }}

      - name: Push to personal repo
        run: |
          git config --global user.name "RamtinRamzani"
          git config --global user.email "ramtinramzani76@gmail.com"
          git remote set-url origin https://$GH_TOKEN@github.com/RamtinRamzani/e-commerce-app.git
          git push --mirror
